* QFieldCloud CLI client
  This is a simple CLI client for QFieldCloud created for testing
  purposes.

  The CLI module has the [[https://palletsprojects.com/p/click/][Click]] package as requirement

** Create a new user
   #+begin_src sh
     python client.py register-user giulia password1234
   #+end_src

** Login with an existing user
   #+begin_src sh
     python client.py login giulia password1234
   #+end_src

** Store the token in an environment variable
   All the commands that need the token, will look at the
   =QFIELDCLOUD_TOKEN= for the token, so it's not necessary to pass
   the token to the commands every time.
   #+begin_src sh
     export QFIELDCLOUD_TOKEN="3e35aed084e18cc0d96371b20049cd28f58d81eb"
   #+end_src

** Create a new QFieldCloud project
   #+begin_src sh
     python client.py create-project proba demo_user "demo project"
   #+end_src
   By default the new created project is a private project. To create
   a public project you can use the =--public= flag:

   #+begin_src sh
     python client.py create-project proba demo_user "demo project" --private
   #+end_src

** List projects
   List projects owned by the authenticated user or that the
   authenticated user has explicit permission to access (i.e. she is a
   project collaborator)
   #+begin_src sh
     python client.py projects
   #+end_src

   To include all public projects use the flag =--include-public=:
   #+begin_src sh
     python client.py projects --include-public
   #+end_src

** Push a file
   The project id should be passed to the command
   #+begin_src sh
     python client.py push-file 68ea7981-970f-4c57-9c73-04f7ba2fab2c /path/of/local/file.txt relative/path/of/remote/file.txt
   #+end_src

** Push a directory
   Pushes a directory and all its contents to the project with specified id. By default, the command will upload all the available files recursively. This behavior can be limited by passing `--filter-glob` and `--no-recursive` CLI options.
   #+begin_src sh
     python client.py push-files 68ea7981-970f-4c57-9c73-04f7ba2fab2c /path/of/local/project
   #+end_src

** Pull a file
   #+begin_src sh
     python client.py pull-file 68ea7981-970f-4c57-9c73-04f7ba2fab2c relative/path/of/remote/file.txt local_file.txt
   #+end_src

   To download a specific version of the file
   #+begin_src sh
     python client.py pull-file 68ea7981-970f-4c57-9c73-04f7ba2fab2c hello.txt hello.txt --version 2020-05-11T06:01:42.493157Z
   #+end_src

** Delete a file
   Deletes the specified remote file or directory
   #+begin_src sh
     python client.py delete-file 68ea7981-970f-4c57-9c73-04f7ba2fab2c /path/to/file.jpg
   #+end_src

** List files of a project
   #+begin_src sh
     python client.py list-files 68ea7981-970f-4c57-9c73-04f7ba2fab2c
   #+end_src
