# Generated by Django 2.2 on 2019-11-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_qgisproject_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qgisproject',
            name='upload',
            field=models.FileField(default='Pippo', upload_to='uploads/'),
        ),
    ]
