# Generated by Django 2.2.6 on 2019-11-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genericfile',
            old_name='upload',
            new_name='datafile',
        ),
        migrations.RemoveField(
            model_name='genericfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='genericfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
