# Generated by Django 2.2.6 on 2019-11-28 16:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_permission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='Collaborator',
        ),
    ]
