# Generated by Django 2.2.6 on 2019-11-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_genericfile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericfile',
            name='datafile',
        ),
        migrations.AddField(
            model_name='genericfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericfile',
            name='filename',
            field=models.CharField(default='poldo', max_length=255),
            preserve_default=False,
        ),
    ]
