# Generated by Django 2.2.6 on 2019-11-18 15:18

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191118_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericfile',
            name='datafile',
            field=models.FileField(default=None, upload_to=projects.models.user_directory_path),
            preserve_default=False,
        ),
    ]
