# Generated by Django 2.2.6 on 2019-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_organizationrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationrole',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'member')], default=2),
        ),
    ]
