services:
  app:
    environment:
      QFIELDCLOUD_CUSTOM_CA_PATH: ${QFIELDCLOUD_CUSTOM_CA_PATH}
      QFIELDCLOUD_CUSTOM_CA_HOST_PATH: ${PWD}/${QFIELDCLOUD_CUSTOM_CA_HOST_PATH}
      REQUESTS_CA_BUNDLE: ${QFIELDCLOUD_CUSTOM_CA_PATH}
      SSL_CERT_FILE: ${QFIELDCLOUD_CUSTOM_CA_PATH}
    volumes:
      - ${PWD}/${QFIELDCLOUD_CUSTOM_CA_HOST_PATH}:${QFIELDCLOUD_CUSTOM_CA_PATH}:ro

  worker_wrapper:
    environment:
      QFIELDCLOUD_CUSTOM_CA_PATH: ${QFIELDCLOUD_CUSTOM_CA_PATH}
      QFIELDCLOUD_CUSTOM_CA_HOST_PATH: ${PWD}/${QFIELDCLOUD_CUSTOM_CA_HOST_PATH}
    volumes:
      - ${PWD}/${QFIELDCLOUD_CUSTOM_CA_HOST_PATH}:${QFIELDCLOUD_CUSTOM_CA_PATH}:ro
