version: '3.9'

services:

  app:
    image: ${QFIELDCLOUD_IMAGE_NAME_FOR_APP}
    build:
      context: ./docker-app
      target: webserver_runtime
      network: host
      args:
        - DEBUG_BUILD=1
    ports:
      # allow direct access without nginx
      - ${DJANGO_DEV_PORT}:8000
      - ${DEBUG_DEBUGPY_APP_PORT:-5678}:5678
    volumes:
      # mount the source for live reload
      - ./docker-app/qfieldcloud:/usr/src/app/qfieldcloud
    command: python3 -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  pipcompile: &default-django
    build:
      context: ./docker-app
      target: build
      network: host
    profiles:
      - donotstart
    volumes:
      # mount the source for live reload
      - ./docker-app/requirements:/requirements
    command: bash -c 'for f in /requirements/*.in; do pip-compile --no-strip-extras -o "$${f%.in}.txt" "$$f"; done'

  worker_wrapper:
    image: ${QFIELDCLOUD_IMAGE_NAME_FOR_WORKER_WRAPPER}
    build:
      context: ./docker-app
      network: host
      target: worker_wrapper_runtime
      args:
        - DEBUG_BUILD=1
    ports:
      - ${DEBUG_DEBUGPY_WORKER_WRAPPER_PORT:-5679}:5679
    environment:
      QFIELDCLOUD_LIBQFIELDSYNC_VOLUME_PATH: ${QFIELDCLOUD_LIBQFIELDSYNC_VOLUME_PATH}
      QFIELDCLOUD_QFIELDCLOUD_SDK_VOLUME_PATH: ${QFIELDCLOUD_QFIELDCLOUD_SDK_VOLUME_PATH}
    volumes:
      # mount the source for live reload
      - ./docker-app/qfieldcloud:/usr/src/app/qfieldcloud
      - ./docker-app/worker_wrapper:/usr/src/app/worker_wrapper
    command: python3 -m debugpy --listen 0.0.0.0:5679 manage.py dequeue

  memcached:
    ports:
      - "${MEMCACHED_PORT}:11211"

  qgis:
    image: ${QFIELDCLOUD_IMAGE_NAME_FOR_QGIS}
    build:
      context: ./docker-qgis
      network: host
      args:
        DEBUG_BUILD: ${DEBUG}

    volumes:
      # allow local development for `docker-qgis`
      - ./docker-qgis/qfc_worker:/usr/src/qfc_worke:ro
      - ./docker-qgis/entrypoint.py:/usr/src/entrypoint.py:ro
      # allow local development for `libqfieldsync` if host directory present; requires `PYTHONPATH=/libqfieldsync:${PYTHONPATH}`
      - ./docker-qgis/libqfieldsync:/libqfieldsync:ro
      # allow local development for `qfieldcloud-sdk-python` if host directory present; requires `PYTHONPATH=/qfieldcloud-sdk-python:${PYTHONPATH}`
      - ./docker-qgis/qfieldcloud-sdk-python:/qfieldcloud-sdk-python:ro

  nginx:
    image: ${QFIELDCLOUD_IMAGE_NAME_FOR_NGINX}
    build:
      context: ./docker-nginx
