# Generated by Django 5.2.14 on 2026-07-06 07:52

import datetime
import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import qfieldcloud.core.fields
import qfieldcloud.core.validators
import qfieldcloud.project.models


def move_content_type(apps, schema_editor):
    """
    Project was moved from the `core` app to this app above via
    SeparateDatabaseAndState, which only changes Django's model state, not
    the database. Left alone, the next `post_migrate` signal would create a
    fresh ContentType("project", "project") row alongside the existing
    ContentType("core", "project") row, orphaning anything that already
    references the old one (notifications, audit log, permissions, ...).
    Renaming the existing row in place - within the same migration, before
    `post_migrate` ever runs - means the new row never gets created, so
    there is nothing to reconcile.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")

    old_ct = ContentType.objects.filter(app_label="core", model="project").first()
    if old_ct is None:
        return

    old_ct.app_label = "project"
    old_ct.save(update_fields=["app_label"])


def reverse_move_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="project", model="project").update(
        app_label="core"
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0103_detach_project_fks_from_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Only letters, numbers, underscores, hyphens and dots are allowed.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9-_\\.]+$",
                                "Only letters, numbers, underscores, hyphens and dots are allowed.",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("the_qgis_file_name", models.TextField(blank=True, null=True)),
                ("project_details", models.JSONField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Projects marked as public are visible to (but not editable by) anyone.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_storage_bytes", models.PositiveBigIntegerField(default=0)),
                ("data_last_updated_at", models.DateTimeField(blank=True, null=True)),
                ("data_last_packaged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "repackaging_cache_expire",
                    models.DurationField(
                        default=datetime.timedelta(seconds=3600),
                        validators=[
                            django.core.validators.MinValueValidator(
                                datetime.timedelta(seconds=60)
                            )
                        ],
                    ),
                ),
                (
                    "overwrite_conflicts",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, QFieldCloud will automatically overwrite conflicts in this project. Disabling this will force the project manager to manually resolve all the conflicts.",
                    ),
                ),
                (
                    "has_restricted_projectfiles",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, modifications of QGIS project configuration (.qgs, qgz, qgd) and QField project plugins files will be restricted to managers and administrators.",
                        verbose_name="Restrict project files",
                    ),
                ),
                (
                    "thumbnail",
                    qfieldcloud.core.fields.DynamicStorageFileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=qfieldcloud.project.models.get_project_thumbnail_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("png", "jpg")
                            ),
                            qfieldcloud.core.validators.MaxImageDimensionValidator(
                                10000
                            ),
                            qfieldcloud.core.validators.MaxFileSizeValidator(5242880),
                        ],
                        verbose_name="Thumbnail Picture",
                    ),
                ),
                (
                    "storage_keep_versions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Use this value to limit the maximum number of file versions. If empty, your current plan's default will be used. Not configurable for free users.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="File versions to keep",
                    ),
                ),
                (
                    "packaging_offliner",
                    models.CharField(
                        choices=[
                            ("qgiscore", "QGIS Core Offline Editing (deprecated)"),
                            ("pythonmini", "Optimized Packager"),
                        ],
                        default="pythonmini",
                        help_text='The Packaging Offliner packages data for offline use with QField. The new "Optimized Packager" should be preferred over the deprecated "QGIS Core Offline Editing" for new projects.',
                        max_length=100,
                        verbose_name="Packaging Offliner",
                    ),
                ),
                (
                    "file_storage",
                    models.CharField(
                        default=qfieldcloud.project.models.get_project_file_storage_default,
                        help_text="Which file storage provider should be used for the storing the project related files.",
                        max_length=100,
                        validators=[
                            qfieldcloud.core.validators.file_storage_name_validator
                        ],
                        verbose_name="File storage",
                    ),
                ),
                (
                    "qgis_version",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="The QGIS project version as detected from the uploaded project file.",
                        max_length=100,
                        null=True,
                        verbose_name="QGIS project version",
                    ),
                ),
                (
                    "file_storage_migrated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="File Storage Migrated At",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        help_text="If not null, it means that the project is being migrated, and the datetime represents when the project was temporarily locked. Locking is internal QFieldCloud mechanism related to file storage migration or other file operations.",
                        null=True,
                        verbose_name="Locked at",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False,
                        help_text="If set to true, the project will always appear on top of the project list, no matter the sorting. If multiple projects are featured, they will be sorted by the user defined sorting.",
                        verbose_name="Is featured",
                    ),
                ),
                (
                    "attachments_file_storage",
                    models.CharField(
                        default=qfieldcloud.project.models.get_project_attachments_file_storage_default,
                        help_text="Which file storage provider should be used for storing the project attachments files.",
                        max_length=100,
                        validators=[
                            qfieldcloud.core.validators.file_storage_name_validator
                        ],
                        verbose_name="Attachments file storage",
                    ),
                ),
                (
                    "is_attachment_download_on_demand",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, attachment files should be downloaded on demand with QField.",
                        verbose_name="On demand attachment files download",
                    ),
                ),
                (
                    "are_attachments_versioned",
                    models.BooleanField(
                        default=qfieldcloud.project.models.get_project_are_attachments_versioned_default,
                        help_text="If enabled, attachment files will make use of the file versioning system. If disabled, only the latest version of each attachment file will be kept, and stored with the extension in the filename.",
                        verbose_name="Versioned attachment files",
                    ),
                ),
                (
                    "restricted_data_last_updated_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Restricted data last updated at",
                    ),
                ),
                (
                    "last_package_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_job_of",
                        to="core.packagejob",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="The project owner can be either you or any of the organization you are member of.",
                        limit_choices_to=models.Q(("type__in", [1, 2])),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "owner__username", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "name"), name="project_owner_name_uniq"
                    )
                ],
            },
        ),
    ]

    operations = [
        migrations.RunPython(move_content_type, reverse_move_content_type),
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
    ]
