# Generated by Django 5.2.14 on 2026-07-06 12:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models

import qfieldcloud.project.models


def move_content_type(apps, schema_editor):
    """See the identically-named function in 0001_initial.py."""
    ContentType = apps.get_model("contenttypes", "ContentType")

    old_ct = ContentType.objects.filter(app_label="core", model="projectseed").first()
    if old_ct is None:
        return

    old_ct.app_label = "project"
    old_ct.save(update_fields=["app_label"])


def reverse_move_content_type(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="project", model="projectseed").update(
        app_label="core"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0001_initial"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="ProjectSeed",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="seed",
                        serialize=False,
                        to="project.project",
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "xlsform_file",
                    models.FileField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        upload_to=qfieldcloud.project.models.get_seed_xlsform_upload_to,
                    ),
                ),
                ("settings", models.JSONField()),
                (
                    "clone_from_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_seeds",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]

    operations = [
        migrations.RunPython(move_content_type, reverse_move_content_type),
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
