# Generated by Django 5.2.14 on 2026-07-08 11:34

from django.db import migrations, models

SHARED_DATASETS_PROJECT_NAME = "shared_datasets"


def set_shared_datasets_project_type(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    Project.objects.filter(name=SHARED_DATASETS_PROJECT_NAME).update(project_type=2)


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_projectseed"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.IntegerField(
                choices=[(1, "Regular"), (2, "Shared Datasets")], default=1
            ),
        ),
        migrations.RunPython(
            set_shared_datasets_project_type, migrations.RunPython.noop
        ),
    ]
