# Generated by Django 5.2.14 on 2026-07-09 10:28

import django.db.models.deletion
from django.db import migrations, models


def backfill_the_qgis_file(apps, schema_editor):
    FILE_TYPE_PROJECT_FILE = 1

    Project = apps.get_model("project", "Project")
    File = apps.get_model("filestorage", "File")

    for project in Project.objects.filter(the_qgis_file_name__isnull=False):
        file = File.objects.filter(
            project=project,
            name=project.the_qgis_file_name,
            file_type=FILE_TYPE_PROJECT_FILE,
        ).first()

        if file is None:
            continue

        project.the_qgis_file_id = file.id
        project.save(update_fields=["the_qgis_file"])


def restore_the_qgis_file_name(apps, schema_editor):
    Project = apps.get_model("project", "Project")

    project_qs = Project.objects.select_related("the_qgis_file").filter(
        the_qgis_file__isnull=False
    )
    for project in project_qs:
        project.the_qgis_file_name = project.the_qgis_file.name
        project.save(update_fields=["the_qgis_file_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0009_alter_file_project"),
        ("project", "0003_project_project_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="the_qgis_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="filestorage.file",
            ),
        ),
        migrations.RunPython(
            backfill_the_qgis_file,
            restore_the_qgis_file_name,
        ),
        migrations.RemoveField(
            model_name="project",
            name="the_qgis_file_name",
        ),
    ]
