# Generated by Django 5.2.16 on 2026-07-23 15:33

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_project_the_qgis_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlimProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Only letters, numbers, underscores, hyphens and dots are allowed.",
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9-_\\.]+$",
                                "Only letters, numbers, underscores, hyphens and dots are allowed.",
                            )
                        ],
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Projects marked as public are visible to (but not editable by) anyone.",
                    ),
                ),
            ],
            options={
                "db_table": "project_project",
                "managed": False,
            },
        ),
    ]
