# Generated by Django 5.2.16 on 2026-07-22 21:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0009_alter_file_project"),
        ("project", "0004_project_the_qgis_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="QgisProject",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        help_text="The QFieldCloud project that this QGIS project belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="qgis_project",
                        serialize=False,
                        to="project.project",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Project name as defined in the QGIS project file."
                    ),
                ),
                (
                    "qgis_version",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="The QGIS project version as detected from the uploaded project file.",
                        max_length=100,
                        verbose_name="QGIS project version",
                    ),
                ),
                (
                    "crs",
                    models.TextField(
                        help_text="The coordinate reference system of the project as EPSG code."
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="The extent of the project in WGS84 coordinates.",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#ffffff",
                        help_text="The background color of the project as a hex color code.",
                        max_length=7,
                    ),
                ),
                (
                    "custom_properties",
                    models.JSONField(
                        default=dict,
                        help_text="A dictionary of custom properties that can be used to store\n            additional information about the project. QFieldSync configured properties are set here.\n            ",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_version",
                    models.OneToOneField(
                        help_text="The QGIS file version that this project belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qgis_project",
                        to="filestorage.fileversion",
                    ),
                ),
            ],
        ),
    ]
