# Generated by Django 5.2.16 on 2026-07-24 20:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_qgisproject"),
    ]

    operations = [
        migrations.CreateModel(
            name="QgisLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qgis_layer_id", models.TextField(help_text="QGIS layer id.")),
                ("name", models.TextField(help_text="QGIS layer name.")),
                (
                    "crs",
                    models.TextField(
                        blank=True,
                        help_text="The coordinate reference system of the layer as EPSG code. Empty for non-spatial layers, e.g. a database table with no geometry column.",
                    ),
                ),
                (
                    "geom_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Point"),
                            (1, "Line"),
                            (2, "Polygon"),
                            (3, "Unknown"),
                            (4, "Null"),
                        ],
                        help_text="The geometry type of the layer.",
                    ),
                ),
                (
                    "wkb_type_name",
                    models.CharField(
                        blank=True,
                        help_text="The WKB type of the layer, stored by name since the WKB type enum is very big.",
                        max_length=50,
                    ),
                ),
                (
                    "layer_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Vector"),
                            (1, "Raster"),
                            (2, "Plugin"),
                            (3, "Mesh"),
                            (4, "VectorTile"),
                            (5, "Annotation"),
                            (6, "PointCloud"),
                            (7, "Group"),
                            (8, "TiledScene"),
                        ],
                        help_text="The type of the layer, e.g. vector, raster, etc.",
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(
                        blank=True,
                        help_text="The name of the data provider, e.g. `ogr`, `gdal`, `postgres`.",
                        max_length=50,
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        help_text="The order position of the layer within the project."
                    ),
                ),
                (
                    "datasource",
                    models.TextField(
                        blank=True,
                        help_text="QGIS layer datasource string. Empty for layers with no data source, e.g. group layers.",
                    ),
                ),
                (
                    "file_name",
                    models.TextField(
                        blank=True, help_text="The (main) filename in the datasource."
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        default=False, help_text="Whether the layer is valid."
                    ),
                ),
                (
                    "is_localized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the layer is using a localized dataset.",
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        choices=[
                            ("no_error", "No error"),
                            ("invalid_layer", "Invalid layer"),
                            ("localized_dataprovider", "Localized data provider"),
                            ("invalid_dataprovider", "Invalid data provider"),
                            ("missing_dataprovider", "Missing data provider"),
                        ],
                        default="no_error",
                        help_text="A code representing the error reason if the layer is not valid.",
                        max_length=100,
                    ),
                ),
                (
                    "error_summary",
                    models.TextField(
                        blank=True,
                        help_text="A short summary of the error, if the layer is not valid.",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="The full error message from QGIS, if the layer is not valid.",
                    ),
                ),
                (
                    "provider_error_summary",
                    models.TextField(
                        blank=True,
                        help_text="A short summary of the data provider error, if the data provider is not valid.",
                    ),
                ),
                (
                    "provider_error_message",
                    models.TextField(
                        blank=True,
                        help_text="The full data provider error, if the data provider is not valid.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qfs_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="A dict of settings configured by QFieldSync and consumed by libqfieldsync, QFieldSync, QField and QFieldCloud.",
                    ),
                ),
                (
                    "qgis_project",
                    models.ForeignKey(
                        help_text="QGIS project that this layer belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="project.qgisproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "QGIS layer",
                "verbose_name_plural": "QGIS layers",
                "ordering": ["qgis_project", "ordering"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("qgis_project", "qgis_layer_id"),
                        name="layer_qgis_project_qgis_layer_id_uniq",
                    )
                ],
            },
        ),
    ]
