# Generated by Django 5.2.16 on 2026-08-03 05:55

from django.db import migrations, models


def convert_project_type_to_text(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    Project.objects.filter(project_type="1").update(project_type="regular")
    Project.objects.filter(project_type="2").update(project_type="shared_datasets")


def reverse_convert_project_type_to_text(apps, schema_editor):
    Project = apps.get_model("project", "Project")
    Project.objects.filter(project_type="shared_datasets").update(project_type="2")
    Project.objects.filter(project_type="regular").update(project_type="1")


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_qgislayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("shared_datasets", "Shared Datasets"),
                ],
                default="regular",
                max_length=32,
            ),
        ),
        migrations.RunPython(
            convert_project_type_to_text, reverse_convert_project_type_to_text
        ),
    ]
