# Generated by Django 5.2.16 on 2026-08-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_alter_project_project_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular"),
                    ("shared_datasets", "Shared Datasets"),
                    ("template", "Template"),
                ],
                default="regular",
                max_length=32,
            ),
        ),
    ]
