# Generated by Django 5.2.17 on 2026-08-14 15:35

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_project_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="QgisLayerField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        help_text="The position in order of the field within the layer."
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Field name as defined in the QGIS layer data source."
                    ),
                ),
                (
                    "alias",
                    models.TextField(
                        blank=True,
                        help_text="Optional user-facing alias configured in QGIS.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional field comment or description configured in QGIS.",
                    ),
                ),
                (
                    "type",
                    models.PositiveIntegerField(
                        choices=[
                            (0, "UnknownType"),
                            (1, "Bool"),
                            (2, "Int"),
                            (3, "UInt"),
                            (4, "LongLong"),
                            (5, "ULongLong"),
                            (6, "Double"),
                            (32, "Long"),
                            (33, "Short"),
                            (34, "Char"),
                            (35, "ULong"),
                            (36, "UShort"),
                            (37, "UChar"),
                            (38, "Float"),
                            (31, "VoidStar"),
                            (7, "QChar"),
                            (10, "QString"),
                            (11, "QStringList"),
                            (12, "QByteArray"),
                            (13, "QBitArray"),
                            (14, "QDate"),
                            (15, "QTime"),
                            (16, "QDateTime"),
                            (17, "QUrl"),
                            (18, "QLocale"),
                            (19, "QRect"),
                            (20, "QRectF"),
                            (21, "QSize"),
                            (22, "QSizeF"),
                            (23, "QLine"),
                            (24, "QLineF"),
                            (25, "QPoint"),
                            (26, "QPointF"),
                            (29, "QEasingCurve"),
                            (30, "QUuid"),
                            (41, "QVariant"),
                            (42, "QModelIndex"),
                            (50, "QPersistentModelIndex"),
                            (44, "QRegularExpression"),
                            (45, "QJsonValue"),
                            (46, "QJsonObject"),
                            (47, "QJsonArray"),
                            (48, "QJsonDocument"),
                            (49, "QByteArrayList"),
                            (39, "QObjectStar"),
                            (40, "SChar"),
                            (43, "Void"),
                            (51, "Nullptr"),
                            (8, "QVariantMap"),
                            (9, "QVariantList"),
                            (28, "QVariantHash"),
                            (58, "QVariantPair"),
                            (52, "QCborSimpleType"),
                            (53, "QCborValue"),
                            (54, "QCborArray"),
                            (55, "QCborMap"),
                            (56, "Char16"),
                            (57, "Char32"),
                            (59, "Int128"),
                            (60, "UInt128"),
                            (61, "Float128"),
                            (62, "BFloat16"),
                            (63, "Float16"),
                            (4096, "QFont"),
                            (4097, "QPixmap"),
                            (4098, "QBrush"),
                            (4099, "QColor"),
                            (4100, "QPalette"),
                            (4101, "QIcon"),
                            (4102, "QImage"),
                            (4103, "QPolygon"),
                            (4104, "QRegion"),
                            (4105, "QBitmap"),
                            (4106, "QCursor"),
                            (4107, "QKeySequence"),
                            (4108, "QPen"),
                            (4109, "QTextLength"),
                            (4110, "QTextFormat"),
                            (4112, "QTransform"),
                            (4113, "QMatrix4x4"),
                            (4114, "QVector2D"),
                            (4115, "QVector3D"),
                            (4116, "QVector4D"),
                            (4117, "QQuaternion"),
                            (4118, "QPolygonF"),
                            (4119, "QColorSpace"),
                            (8192, "QSizePolicy"),
                            (65536, "User"),
                        ],
                        help_text="QGIS field type as a Qt type enum value.",
                        null=True,
                    ),
                ),
                (
                    "type_display",
                    models.CharField(
                        blank=True,
                        help_text="QGIS field type display name",
                        max_length=100,
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        default=0, help_text="Declared field length reported by QGIS."
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(
                        default=0,
                        help_text="Declared numeric precision reported by QGIS.",
                    ),
                ),
                (
                    "is_not_null_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the not-null constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "constraint_expression",
                    models.TextField(
                        blank=True, help_text="Optional QGIS constraint expression."
                    ),
                ),
                (
                    "constraint_expression_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional human-readable error message when the constraint expression is violated.",
                    ),
                ),
                (
                    "constraint_expression_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the expression constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "is_unique_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the unique constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="QGIS default value expression for new features.",
                    ),
                ),
                (
                    "set_default_value_on_update",
                    models.BooleanField(
                        default=False,
                        help_text="Whether QGIS reapplies the default value when a feature is updated.",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        blank=True,
                        help_text="QGIS editor widget type configured for the field.",
                        max_length=100,
                    ),
                ),
                (
                    "widget_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="QGIS editor widget configuration.",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        help_text="The QGIS layer that owns this field.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="project.qgislayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "QGIS layer field",
                "verbose_name_plural": "QGIS layer fields",
                "ordering": ["layer", "ordering"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layer", "name"),
                        name="field_qgis_layer_qgis_field_name_uniq",
                    )
                ],
            },
        ),
    ]
