# Generated by Django 5.2.17 on 2026-08-17 12:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_project_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="qgisproject",
            name="area_of_interest",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True,
                help_text="The area of interest of the project in WGS84 coordinates.",
                null=True,
                srid=4326,
            ),
        ),
    ]
