# Generated by Django 5.2.17 on 2026-08-12 13:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0009_project_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="QgisLayerField",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ordering",
                    models.PositiveIntegerField(
                        help_text="The position in order of the field within the layer."
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Field name as defined in the QGIS layer data source."
                    ),
                ),
                (
                    "alias",
                    models.TextField(
                        blank=True,
                        help_text="Optional user-facing alias configured in QGIS.",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Optional field comment or description configured in QGIS.",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        help_text="QGIS field type name, such as integer, text, or date.",
                        max_length=100,
                    ),
                ),
                (
                    "length",
                    models.IntegerField(
                        default=0, help_text="Declared field length reported by QGIS."
                    ),
                ),
                (
                    "precision",
                    models.IntegerField(
                        default=0,
                        help_text="Declared numeric precision reported by QGIS.",
                    ),
                ),
                (
                    "is_not_null_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the not-null constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "constraint_expression",
                    models.TextField(
                        blank=True, help_text="Optional QGIS constraint expression."
                    ),
                ),
                (
                    "constraint_expression_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional human-readable error message when the constraint expression is violated.",
                    ),
                ),
                (
                    "constraint_expression_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the expression constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "is_unique_strength",
                    models.CharField(
                        choices=[
                            ("not_set", "Not set"),
                            ("hard", "Hard"),
                            ("soft", "Soft"),
                        ],
                        default="not_set",
                        help_text="Strength of the unique constraint.",
                        max_length=10,
                    ),
                ),
                (
                    "default_value",
                    models.TextField(
                        blank=True,
                        help_text="QGIS default value expression for new features.",
                    ),
                ),
                (
                    "set_default_value_on_update",
                    models.BooleanField(
                        default=False,
                        help_text="Whether QGIS reapplies the default value when a feature is updated.",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        blank=True,
                        help_text="QGIS editor widget type configured for the field.",
                        max_length=100,
                    ),
                ),
                (
                    "widget_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="QGIS editor widget configuration.",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        help_text="The QGIS layer that owns this field.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="project.qgislayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "QGIS layer field",
                "verbose_name_plural": "QGIS layer fields",
                "ordering": ["layer", "ordering"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("layer", "name"),
                        name="field_qgis_layer_qgis_field_name_uniq",
                    )
                ],
            },
        ),
    ]
