# Generated by Django 5.2.17 on 2026-08-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0010_qgisproject_area_of_interest"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="public_collaborator_role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("reporter", "Reporter"),
                    ("editor", "Editor"),
                ],
                default="reader",
                help_text="The role automatically granted to every user on this project. This setting only takes effect if the project is marked as public.",
                max_length=10,
            ),
        ),
    ]
