# Generated by Django 5.2.17 on 2026-09-03 12:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0011_project_public_collaborator_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="qgislayer",
            name="layer_qgis_project_qgis_layer_id_uniq",
        ),
        migrations.AddConstraint(
            model_name="qgislayer",
            constraint=models.UniqueConstraint(
                models.F("qgis_project"),
                django.db.models.functions.text.MD5("qgis_layer_id"),
                name="layer_qgis_project_qgis_layer_id_md5_uniq",
            ),
        ),
    ]
