# Generated by Django 5.2.17 on 2026-09-09 08:42

from django.db import migrations, models

import qfieldcloud.project.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0012_remove_qgislayer_layer_qgis_project_qgis_layer_id_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projectseed",
            name="json2qgis_file",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=qfieldcloud.project.models.get_seed_json2qgis_upload_to,
            ),
        ),
    ]
