# Generated by Django 2.2.6 on 2020-02-12 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import qfieldcloud.apps.model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='member',
            field=models.ForeignKey(limit_choices_to=models.Q(user_type=1), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(limit_choices_to=models.Q(user_type=2), on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Project name', max_length=255, validators=[django.core.validators.RegexValidator('^[-a-zA-Z0-9_]*$', 'Only letters, numbers, underscores or hyphens are allowed.'), django.core.validators.RegexValidator('^.{3,}$', 'The project name must be at least 3 characters long.'), django.core.validators.RegexValidator('^[a-zA-Z].*$', 'The project name must begin with a letter.'), qfieldcloud.apps.model.models.reserved_words_validator]),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='collaborator',
            field=models.ForeignKey(limit_choices_to=models.Q(type=1), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='model.Project'),
        ),
    ]
