# Generated by Django 2.2.6 on 2020-03-09 08:56

from django.db import migrations, models
import django.db.models.deletion
import qfieldcloud.apps.model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_file_absolute_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='stored_file',
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stored_file', models.FileField(upload_to=qfieldcloud.apps.model.models.FileVersion.file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.File')),
            ],
        ),
    ]
