# Generated by Django 2.2.6 on 2020-03-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_auto_20200312_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileversion',
            name='original_path',
        ),
    ]
