# Generated by Django 2.2.6 on 2020-06-08 11:37

from django.db import migrations, models
import qfieldcloud.apps.model.models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_auto_20200608_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltafile',
            name='file',
            field=models.FileField(upload_to=qfieldcloud.apps.model.models.DeltaFile.file_path),
        ),
    ]
