# Generated by Django 2.2.6 on 2020-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_delete_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltafile',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deltafile',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'BUSY'), (3, 'APPLIED'), (4, 'APPLIED_WITH_CONFLICTS'), (5, 'ERROR')], default=1),
        ),
    ]
