# Generated by Django 2.2.14 on 2020-07-24 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_auto_20200612_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcollaborator',
            name='collaborator',
            field=models.ForeignKey(limit_choices_to=models.Q(user_type=1), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
