# Generated by Django 3.2.13 on 2022-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_populate_account_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="max_organization_members",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum organization members allowed for particular subscription plan. Set 0 to allow unlimited organization members.",
            ),
        ),
    ]
