# Generated by Django 3.2.15 on 2022-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_populate_plans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Person"), (2, "Organization"), (3, "Team")], default=1
            ),
        ),
    ]
