# Generated by Django 3.2.16 on 2023-01-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_auto_20220923_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_cancellable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_storage_modifiable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="upgradable_to",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
