# Generated by Django 3.2.16 on 2023-01-13 07:06

import uuid

import migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0004_auto_20220923_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_cancellable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_storage_modifiable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="upgradable_to",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name="CurrentSubscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive_draft", "Inactive Draft"),
                            ("inactive_draft_expired", "Inactive Draft Expired"),
                            ("inactive_requested_create", "Inactive Requested Create"),
                            ("inactive_awaits_payment", "Inactive Awaits Payment"),
                            ("active_paid", "Active Paid"),
                            ("active_past_due", "Active Past Due"),
                            ("inactive_cancelled", "Inactive Cancelled"),
                        ],
                        default="inactive_draft",
                        max_length=100,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "requested_cancel_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Requested cancel at"
                    ),
                ),
                (
                    "active_since",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Active since"
                    ),
                ),
                (
                    "active_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Active until"
                    ),
                ),
                (
                    "billing_cycle_anchor_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("current_period_since", models.DateTimeField(blank=True, null=True)),
                ("current_period_until", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "current_subscriptions_vw",
                "managed": False,
            },
        ),
        migrate_sql.operations.CreateSQL(
            name="current_subscriptions_vw",
            sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
            reverse_sql="\n            DROP VIEW current_subscriptions_vw\n        ",
        ),
    ]
