# Generated by Django 3.2.18 on 2023-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_auto_20230113_0806"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
    ]
