# Generated by Django 3.2.18 on 2023-04-26 20:22

import migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0005_auto_20230113_0806"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="packagetype",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are for internal purposes only and will never be shown to the end users.",
                null=True,
                verbose_name="Admin notes",
            ),
        ),
        # NOTE we need to recreate the view, since we just added a new `subscription_subscription.notes` column
        migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\n            DROP VIEW IF EXISTS current_subscriptions_vw\n        ",
            reverse_sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
        ),
        migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
            reverse_sql="\n            DROP VIEW current_subscriptions_vw\n        ",
        ),
    ]
