# Generated by Django 4.2.25 on 2025-11-10 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="is_metered",
        ),
    ]
