# Generated by Django 4.2.19 on 2025-07-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="max_organization_members",
            new_name="default_max_organization_members",
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_organization_members",
            field=models.IntegerField(
                default=0,
                help_text="Maximum organization members allowed for this subscription.Used for enforcing seat limits on a per-subscription basis for specific plans.",
            ),
        ),
    ]
