# Generated by Django 4.2.19 on 2025-08-07 22:29

import migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="is_metered",
            new_name="is_seat_flexible",
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_organization_members",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum organization members allowed for this subscription.Used for enforcing seat limits on a per-subscription basis for specific plans.",
            ),
        ),
        # NOTE we need to recreate the view, since we just added a new `subscription_subscription.notes` column
        migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\n            DROP VIEW IF EXISTS current_subscriptions_vw\n        ",
            reverse_sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
        ),
        migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
            reverse_sql="\n            DROP VIEW current_subscriptions_vw\n        ",
        ),
    ]
