# Generated by Django 4.2.17 on 2025-02-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="plan",
            new_name="regular_plan",
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trial ends at"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subscription.plan",
            ),
        ),
    ]
