# Generated by Django 4.2.19 on 2025-08-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_seat_flexible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="max_organization_members",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum organization members allowed for this subscription.Used for enforcing seat limits on a per-subscription basis for specific plans.",
            ),
        ),
    ]
