# Generated by Django 4.2.17 on 2025-02-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0006_auto_20230426_2222"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="plan",
            new_name="regular_plan",
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Trial ends at"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="subscription.plan",
            ),
        ),
        migrations.RunSQL(
            sql="""
                DROP VIEW IF EXISTS current_subscriptions_vw;
                CREATE VIEW current_subscriptions_vw AS
                SELECT
                    id,
                    uuid,
                    regular_plan_id,  -- Now includes regular plan
                    trial_plan_id,    -- Include the trial plan ID
                    account_id,
                    status,
                    created_by_id,
                    created_at,
                    updated_at,
                    requested_cancel_at,
                    active_since,
                    active_until,
                    trial_ends_at,
                    billing_cycle_anchor_at,
                    current_period_since,
                    current_period_until,
                    notes
                FROM subscription_subscription
                WHERE active_since < now()
                AND (active_until IS NULL OR active_until > now());
            """,
            reverse_sql="DROP VIEW IF EXISTS current_subscriptions_vw;",
        ),
    ]
