# Generated by Django 4.2.26 on 2026-03-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0007_remove_plan_is_metered"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_seat_based",
            field=models.BooleanField(default=False),
        ),
    ]
