# Generated by Django 4.2.19 on 2025-07-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscription",
            "0007_rename_max_organization_members_plan_default_max_organization_members_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_seat_flexible",
            field=models.BooleanField(default=False),
        ),
    ]
