# Generated by Django 4.2.26 on 2026-03-16 16:04

from django.db import migrations, models

DROP_VIEW = "DROP VIEW IF EXISTS current_subscriptions_vw;"

CREATE_VIEW = """\
CREATE VIEW current_subscriptions_vw AS
SELECT *
FROM subscription_subscription
WHERE active_since < now()
AND (active_until IS NULL OR active_until > now());
"""


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0008_plan_is_seat_based"),
    ]

    operations = [
        migrations.RunSQL(
            sql=DROP_VIEW,
            reverse_sql=CREATE_VIEW,
        ),
        migrations.AddField(
            model_name="subscription",
            name="purchased_seats",
            field=models.IntegerField(
                default=-1,
                help_text="Purchased seats for this subscription. Used for enforcing seat limits on a per-subscription basis for specific plans.",
            ),
        ),
        migrations.RunSQL(
            sql=CREATE_VIEW,
            reverse_sql=DROP_VIEW,
        ),
    ]
