# Generated by Django 4.2.19 on 2025-07-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0008_plan_is_seat_flexible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="default_max_organization_members",
            new_name="max_organization_members",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="max_organization_members",
            field=models.IntegerField(
                default=-1,
                help_text="Maximum organization members allowed for this subscription.Used for enforcing seat limits on a per-subscription basis for specific plans.",
            ),
        ),
    ]
