# Generated by Django 4.2.23 on 2025-08-26 06:50

from django.db import migrations, models

import qfieldcloud.billing.integrations.stripe.enums


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0008_drop_plan_is_metered"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="interval",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("month", "Month"),
                    ("week", "Week"),
                    ("year", "Year"),
                ],
                default=qfieldcloud.billing.integrations.stripe.enums.RecurringInterval[
                    "MONTH"
                ],
                max_length=10,
            ),
        ),
        migrations.RunSQL(
            sql="""
                DROP VIEW IF EXISTS current_subscriptions_vw;
                CREATE VIEW current_subscriptions_vw AS
                SELECT
                    *
                FROM subscription_subscription
                WHERE active_since < now()
                  AND (active_until IS NULL OR active_until > now());
            """,
        ),
    ]
