# Generated by Django 5.2.13 on 2026-04-28 12:19

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Cast


def set_storage_threshold(apps, schema_editor):
    # For each plan, calculate the storage threshold
    # Warning threshold is 20% of the storage_mb
    # Critical threshold is 10% of the storage_mb
    Plan = apps.get_model("subscription", "Plan")

    storage_mb_as_bigint = Cast(F("storage_mb"), output_field=models.BigIntegerField())

    Plan.objects.all().update(
        storage_threshold_warning_bytes=storage_mb_as_bigint
        * 200000,  # 20% of the storage_mb
        storage_threshold_critical_bytes=storage_mb_as_bigint
        * 100000,  # 10% of the storage_mb
    )


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0009_subscription_purchased_seats"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="storage_threshold_critical_bytes",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Remaining storage threshold critical bytes."
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="storage_threshold_warning_bytes",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Remaining storage threshold warning bytes."
            ),
        ),
        migrations.RunPython(
            set_storage_threshold,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
