# Generated by Django 4.2.19 on 2025-07-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscription",
            "0009_rename_default_max_organization_members_plan_max_organization_members_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="is_metered",
        ),
        migrations.AddField(
            model_name="plan",
            name="usage_type",
            field=models.CharField(
                choices=[("licensed", "Licensed"), ("metered", "Metered")],
                default="licensed",
                help_text="licensed (flat fee per user) or metered (usage-based)",
                max_length=20,
            ),
        ),
    ]
