# Generated by Django 4.2.23 on 2025-08-31 21:43

from django.db import migrations, models

import qfieldcloud.billing.integrations.stripe.enums


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0009_subscription_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagetype",
            name="interval",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("month", "Month"),
                    ("week", "Week"),
                    ("year", "Year"),
                ],
                default=qfieldcloud.billing.integrations.stripe.enums.RecurringInterval[
                    "MONTH"
                ],
                help_text="Recurring interval for this subscription (e.g., month, year)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="packagetype",
            name="type",
            field=models.CharField(choices=[("storage", "Storage")], max_length=100),
        ),
        migrations.AddConstraint(
            model_name="packagetype",
            constraint=models.UniqueConstraint(
                fields=("type", "interval"), name="uniq_packagetype_type_interval"
            ),
        ),
        migrations.RunSQL(
            sql="""
                DROP VIEW IF EXISTS current_subscriptions_vw;
                CREATE VIEW current_subscriptions_vw AS
                SELECT
                    *
                FROM subscription_subscription
                WHERE active_since < now()
                  AND (active_until IS NULL OR active_until > now());
            """,
        ),
    ]
