# Generated by Django 5.2.16 on 2026-07-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0010_plan_storage_threshold_critical_bytes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan used as the trial version of this plan. If set, users can start this plan with a trial period.",
                limit_choices_to={"is_trial": True},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="subscription.plan",
            ),
        ),
    ]
