# Generated by Django 5.2.17 on 2026-08-18 16:31

import django_migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0011_plan_trial_plan"),
    ]

    operations = [
        django_migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\n            DROP VIEW current_subscriptions_vw\n        ",
            reverse_sql="\n            CREATE VIEW current_subscriptions_vw AS\n            SELECT\n                *\n            FROM\n                subscription_subscription\n            WHERE\n                active_since < now()\n                AND (\n                    active_until IS NULL\n                    OR active_until > now()\n                )\n        ",
        ),
        django_migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
            reverse_sql="\nDROP VIEW current_subscriptions_vw\n",
        ),
    ]
