# Generated by Django 5.2.17 on 2026-08-27 12:13

import django.db.models.deletion
import django_migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0012_auto_20260818_1831"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="trial_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="subscription.plan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="initial_subscription_status",
            field=models.CharField(
                choices=[
                    ("inactive_draft", "Inactive Draft"),
                    ("inactive_draft_expired", "Inactive Draft Expired"),
                    ("inactive_requested_create", "Inactive Requested Create"),
                    ("inactive_awaits_payment", "Inactive Awaits Payment"),
                    ("active_paid", "Active Paid"),
                    ("active_past_due", "Active Past Due"),
                    ("inactive_cancelled", "Inactive Cancelled"),
                    ("active_trial", "Active Trial"),
                ],
                default="inactive_draft",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("inactive_draft", "Inactive Draft"),
                    ("inactive_draft_expired", "Inactive Draft Expired"),
                    ("inactive_requested_create", "Inactive Requested Create"),
                    ("inactive_awaits_payment", "Inactive Awaits Payment"),
                    ("active_paid", "Active Paid"),
                    ("active_past_due", "Active Past Due"),
                    ("inactive_cancelled", "Inactive Cancelled"),
                    ("active_trial", "Active Trial"),
                ],
                default="inactive_draft",
                max_length=100,
            ),
        ),
        # force recreate due to new field added
        django_migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\nDROP VIEW current_subscriptions_vw\n",
            reverse_sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
        ),
        django_migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
            reverse_sql="\nDROP VIEW current_subscriptions_vw\n",
        ),
    ]
