# Generated by Django 5.2.17 on 2026-09-21 12:06

import django.db.models.deletion
import django_migrate_sql.operations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0013_alter_subscription_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="trial_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="subscription.plan",
            ),
        ),
        # force recreate due to new field added
        django_migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\nDROP VIEW current_subscriptions_vw\n",
            reverse_sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
        ),
        django_migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
            reverse_sql="\nDROP VIEW current_subscriptions_vw\n",
        ),
    ]
