# Generated by Django 5.2.17 on 2026-08-28 09:39

import django_migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0013_auto_20260827_1413"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="plan",
            new_name="regular_plan",
        ),
        django_migrate_sql.operations.ReverseAlterSQL(
            name="current_subscriptions_vw",
            sql="\nDROP VIEW current_subscriptions_vw\n",
            reverse_sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    *\nFROM\n    subscription_subscription\nWHERE\n    active_since < now()\n    AND (\n        active_until IS NULL\n        OR active_until > now()\n    )\n",
        ),
        django_migrate_sql.operations.AlterSQL(
            name="current_subscriptions_vw",
            sql="\nCREATE VIEW current_subscriptions_vw AS\nSELECT\n    s.id,\n    s.uuid,\n    s.regular_plan_id,\n    CASE\n        WHEN s.trial_expires_at > now() AND s.trial_plan_id IS NOT NULL\n        THEN s.trial_plan_id\n        ELSE s.regular_plan_id\n    END AS active_plan_id,\n    s.purchased_seats,\n    s.account_id,\n    s.status,\n    s.created_by_id,\n    s.created_at,\n    s.updated_at,\n    s.requested_cancel_at,\n    s.active_since,\n    s.active_until,\n    s.billing_cycle_anchor_at,\n    s.current_period_since,\n    s.current_period_until,\n    s.notes,\n    s.trial_plan_id,\n    s.trial_expires_at\nFROM subscription_subscription s\nWHERE s.active_since < now()\nAND (s.active_until IS NULL OR s.active_until > now());\n",
            reverse_sql="\nDROP VIEW current_subscriptions_vw\n",
        ),
    ]
