# Generated by Django 2.2.17 on 2020-11-16 16:01

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deltafile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "PENDING"),
                            (2, "BUSY"),
                            (3, "APPLIED"),
                            (4, "APPLIED_WITH_CONFLICTS"),
                            (5, "NOT_APPLIED"),
                            (6, "ERROR"),
                        ],
                        default=1,
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deltas",
                        to="core.Project",
                    ),
                ),
            ],
        ),
    ]
