# Generated by Django 2.2.17 on 2020-12-14 16:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201203_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delta',
            name='output',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
