# Generated by Django 2.2.17 on 2020-12-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_auto_20201214_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="overwrite_conflicts",
            field=models.BooleanField(default=True),
        ),
    ]
