# Generated by Django 2.2.17 on 2021-01-03 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import qfieldcloud.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_update_site_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Geodb",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        default=qfieldcloud.core.models.random_string,
                        max_length=255,
                    ),
                ),
                (
                    "dbname",
                    models.CharField(
                        default=qfieldcloud.core.models.random_string,
                        max_length=255,
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        default=settings.GEODB_HOST,
                        max_length=255,
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(default=settings.GEODB_PORT),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
