# Generated by Django 2.2.17 on 2021-01-06 08:42

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_auto_20210106_1543"),
    ]

    operations = [
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "STATUS_PENDING"),
                            (2, "STATUS_BUSY"),
                            (3, "STATUS_EXPORTED"),
                            (4, "STATUS_ERROR"),
                        ],
                        default=1,
                    ),
                ),
                ("output", models.TextField(null=True)),
                (
                    "exportlog",
                    django.contrib.postgres.fields.jsonb.JSONField(null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="core.Project",
                    ),
                ),
            ],
        ),
    ]
