# Generated by Django 2.2.17 on 2021-01-06 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_export"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Export",
            new_name="Exportation",
        ),
    ]
