# Generated by Django 2.2.17 on 2021-01-12 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_auto_20210106_0930"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exportation",
            name="output",
        ),
    ]
