# Generated by Django 2.2.17 on 2021-01-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_exportation_output"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="bio",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="is_email_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="location",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="twitter",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="workplace",
            field=models.CharField(default="", max_length=255),
        ),
    ]
