# Generated by Django 2.2.17 on 2021-03-08 00:34

from django.db import migrations, models
from django.db.models.aggregates import Count


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Project = apps.get_model("core", "Project")

        nonunique_projects_data = (
            Project.objects.values("name", "owner")
            .annotate(c=Count("id"))
            .filter(c__gt=1)
        )

        for project_data in nonunique_projects_data:
            count = 0

            for project in Project.objects.filter(
                name=project_data.get("name"), owner_id=project_data.get("owner")
            ):
                count += 1

                if count == 1:
                    continue

                project.name += f"_{count}"
                project.save()

    dependencies = [
        ("core", "0017_auto_20210226_1939"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="project_owner_name_uniq"
            ),
        ),
    ]
