# Generated by Django 2.2.19 on 2021-03-31 01:43

from django.db import migrations, models
from django.db.models.aggregates import Count


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        OrganizationMember = apps.get_model("core", "OrganizationMember")

        duplicated_members_data = (
            OrganizationMember.objects.values("organization", "member")
            .annotate(c=Count("id"))
            .filter(c__gt=1)
        )

        for member_data in duplicated_members_data:
            queryset = OrganizationMember.objects.filter(
                organization=member_data["organization"],
                member=member_data["member"],
            ).order_by("role")

            queryset.exclude(pk=queryset.first().pk).delete()
            queryset.save()

        for organization_member in OrganizationMember.objects.all():
            member = organization_member.member
            organization = organization_member.organization

            if member == organization.organization_owner:
                organization_member.delete()

    dependencies = [
        ("core", "0021_auto_20210330_2209"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="organizationmember",
            constraint=models.UniqueConstraint(
                fields=("organization", "member"),
                name="organization_organization_member_uniq",
            ),
        ),
    ]
