# Generated by Django 2.2.19 on 2021-03-31 20:17

from django.db import migrations, models
from qfieldcloud.core.utils import get_project_files_count, get_qgis_project_file


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Project = apps.get_model("core", "Project")

        for project in Project.objects.all():
            project.files_count = get_project_files_count(project.id)
            project.qgis_project_file = get_qgis_project_file(project.id)
            project.save()

    dependencies = [
        ("core", "0022_auto_20210331_0143"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="files_count",
            field=models.PositiveIntegerField(
                default=0, help_text="The number of files associated with this project."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="qgis_project_file",
            field=models.TextField(
                help_text="The QGIS project file (.qgs, .qgz) associated with this project. Null if no project file uploaded yet.",
                null=True,
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
