# Generated by Django 2.2.19 on 2021-04-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_auto_20210331_0143"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="remaining_invitations",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
