# Generated by Django 2.2.19 on 2021-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_auto_20210407_1247"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_geodb_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Whether the account has the option to create a GeoDB.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_geodb_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the account has the option to create a GeoDB.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="remaining_invitations",
            field=models.PositiveIntegerField(
                default=3,
                help_text="Remaining invitations that can be sent by the user himself.",
            ),
        ),
    ]
