# Generated by Django 3.1.8 on 2021-04-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_auto_20210407_2002"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="content",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="delta",
            name="output",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="exportation",
            name="exportlog",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
