# Generated by Django 3.2 on 2021-04-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    def generate_user_account(apps, schema_editor):
        User = apps.get_model("core", "User")
        UserAccount = apps.get_model("core", "UserAccount")

        for user in User.objects.filter(useraccount=None):
            UserAccount.objects.create(user=user)

    def transfer_is_geodb_enabled_forwards(apps, schema_editor):
        User = apps.get_model("core", "User")

        for user in User.objects.all():
            user.useraccount.is_geodb_enabled = user.is_geodb_enabled

    def transfer_is_geodb_enabled_backwards(apps, schema_editor):
        User = apps.get_model("core", "User")

        for user in User.objects.all():
            user.is_geodb_enabled = user.useraccount.is_geodb_enabled

    dependencies = [
        ("core", "0025_auto_20210407_2306"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="is_geodb_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the account has the option to create a GeoDB.",
            ),
        ),
        migrations.RunPython(
            generate_user_account, reverse_code=migrations.RunPython.noop
        ),
        migrations.RunPython(
            transfer_is_geodb_enabled_forwards,
            reverse_code=transfer_is_geodb_enabled_backwards,
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_geodb_enabled",
        ),
    ]
