# Generated by Django 3.2 on 2021-04-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_project_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["owner__username", "name"]},
        ),
    ]
