# Generated by Django 3.2 on 2021-04-15 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_auto_20210414_1545"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["owner__username", "name"]},
        ),
        migrations.AlterField(
            model_name="project",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
