# Generated by Django 3.2 on 2021-04-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_project_options"),
        ("core", "0028_auto_20210414_1545"),
    ]

    operations = []
