# Generated by Django 3.2 on 2021-04-15 11:59

from django.db import migrations, models


def refactor_roles(apps, schema_editor):
    OrganizationMember = apps.get_model("core", "OrganizationMember")
    ProjectCollaborator = apps.get_model("core", "ProjectCollaborator")
    OrganizationMember.objects.filter(role=1).update(role_str="admin")
    OrganizationMember.objects.filter(role=2).update(role_str="member")
    ProjectCollaborator.objects.filter(role=1).update(role_str="admin")
    ProjectCollaborator.objects.filter(role=2).update(role_str="manager")
    ProjectCollaborator.objects.filter(role=3).update(role_str="editor")
    ProjectCollaborator.objects.filter(role=4).update(role_str="reporter")
    ProjectCollaborator.objects.filter(role=5).update(role_str="reader")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_auto_20210415_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role_str",
            field=models.CharField(
                choices=[("admin", "Admin"), ("member", "Member")],
                default="member",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="projectcollaborator",
            name="role_str",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("manager", "Manager"),
                    ("editor", "Editor"),
                    ("reporter", "Reporter"),
                    ("reader", "Reader"),
                ],
                default="reader",
                max_length=10,
            ),
        ),
        migrations.RunPython(refactor_roles),
        migrations.RemoveField(
            model_name="organizationmember",
            name="role",
        ),
        migrations.RemoveField(
            model_name="projectcollaborator",
            name="role",
        ),
        migrations.RenameField(
            model_name="organizationmember",
            old_name="role_str",
            new_name="role",
        ),
        migrations.RenameField(
            model_name="projectcollaborator",
            old_name="role_str",
            new_name="role",
        ),
    ]
