# Generated by Django 3.2.2 on 2021-05-10 06:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_auto_20210508_1030"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                help_text="Only letters, numbers, underscores, hyphens and dots are allowed.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z0-9-_\\.]+$",
                        "Only letters, numbers, underscores, hyphens and dots are allowed.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="twitter",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="workplace",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
