# Generated by Django 3.2.4 on 2021-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_auto_20210630_1210"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="last_modified_pk",
            field=models.TextField(null=True),
        ),
    ]
