# Generated by Django 3.2.5 on 2021-07-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20210630_1212"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_filename",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("exporting", "Exporting"),
                    ("applying_deltas", "Applying deltas"),
                    ("process_projectfile", "Process QGIS project file"),
                ],
                default="idle",
                max_length=30,
            ),
        ),
    ]
