# Generated by Django 3.2.5 on 2021-07-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail_uri",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Thumbnail Picture URI"
            ),
        ),
    ]
