# Generated by Django 3.2.7 on 2021-10-01 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        # There used to be some operations, which does not affect the database storage, but got outdated.
        # Therefore this migrations become empty.
    ]
