# Generated by Django 3.2.6 on 2021-09-27 20:23

import django.db.models.deletion
import qfieldcloud.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=qfieldcloud.core.models.generate_token_key,
                        max_length=300,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        default=qfieldcloud.core.models.generate_token_expires_at,
                        verbose_name="Expires at",
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User-Agent")),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("browser", "Browser"),
                            ("cli", "Command line interface"),
                            ("sdk", "SDK"),
                            ("qfield", "QField"),
                            ("qfieldsync", "QFieldSync"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=32,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "ordering": ("-created_at",),
            },
        ),
    ]
