# Generated by Django 3.2.7 on 2021-10-01 22:17

import qfieldcloud.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("objects", qfieldcloud.core.models.QFieldCloudUserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", qfieldcloud.core.models.QFieldCloudUserManager()),
            ],
        ),
    ]
