# Generated by Django 3.2.6 on 2021-08-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="worker_label",
            field=models.CharField(
                choices=[
                    ("qfc-qgis-3.20", "qfc-qgis-3.20"),
                    ("qfc-qgis-3.18", "qfc-qgis-3.18"),
                ],
                default="qfc-qgis-3.20",
                max_length=255,
            ),
        ),
    ]
