# Generated by Django 3.2.6 on 2021-08-26 15:40

import qfieldcloud.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_auto_20210705_0837"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="worker_image",
            field=models.CharField(
                default=qfieldcloud.core.models.get_default_worker_image, max_length=255
            ),
        ),
    ]
