# Generated by Django 3.2.7 on 2021-10-05 22:17


from django.conf import settings
from django.db import migrations


def update_site_name(apps, schema_editor):
    site_model = apps.get_model("sites", "Site")
    domain = settings.QFIELDCLOUD_HOST
    name = "QFieldCloud"

    site_model.objects.update_or_create(
        pk=settings.SITE_ID, defaults={"domain": domain, "name": name}
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_auto_20211001_2217"),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
