# Generated by Django 3.2.5 on 2021-07-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_auto_20210708_0809"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessQgisProjectfileJob",
            fields=[
                (
                    "job_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.job",
                    ),
                ),
                ("feedback", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "Job: process QGIS project file",
                "verbose_name_plural": "Jobs: process QGIS project file",
            },
            bases=("core.job",),
        ),
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("export", "Export"),
                    ("delta_apply", "Delta Apply"),
                    ("process_projectfile", "Process QGIS Project File"),
                ],
                max_length=32,
            ),
        ),
    ]
