# Generated by Django 3.2.5 on 2021-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_auto_20210708_0812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("stopped", "Stopped"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=32,
            ),
        ),
    ]
