# Generated by Django 3.2.8 on 2021-10-06 13:38

import django.core.validators
from django.db import migrations, models

import qfieldcloud.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_update_site_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[-a-zA-Z0-9_]+$",
                        "Only letters, numbers, underscores or hyphens are allowed.",
                    ),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z].*$", "The name must begin with a letter."
                    ),
                    django.core.validators.RegexValidator(
                        "^.{3,}$", "The name must be at least 3 characters long."
                    ),
                    qfieldcloud.core.validators.reserved_words_validator,
                ],
                verbose_name="username",
            ),
        ),
    ]
