# Generated by Django 3.2.5 on 2021-07-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Job = apps.get_model("core", "Job")
        ExportJob = apps.get_model("core", "ExportJob")
        ProcessQgisProjectfileJob = apps.get_model("core", "ProcessQgisProjectfileJob")

        for export_job in ExportJob.objects.all():
            job = Job.objects.get(id=export_job.job_ptr_id)
            job.feedback = {
                "legacy": {
                    "exportlog": export_job.exportlog,
                }
            }
            job.save()

        for process_projectfile_job in ProcessQgisProjectfileJob.objects.all():
            job = Job.objects.get(id=process_projectfile_job.job_ptr_id)
            job.feedback = process_projectfile_job.feedback_old
            job.save()

    def backwards_func(apps, schema_editor):
        Job = apps.get_model("core", "Job")
        ExportJob = apps.get_model("core", "ExportJob")
        ProcessQgisProjectfileJob = apps.get_model("core", "ProcessQgisProjectfileJob")

        for export_job in ExportJob.objects.all():
            job = Job.objects.get(id=export_job.job_ptr_id)

            if job.feedback and job.feedback.get("legacy", {}).get("exportlog"):
                export_job.exportlog = job.feedback.get("legacy").get("exportlog")
                export_job.save()

        for process_projectfile_job in ProcessQgisProjectfileJob.objects.all():
            job = Job.objects.get(id=process_projectfile_job.job_ptr_id)
            process_projectfile_job.feedback_old = job.feedback
            process_projectfile_job.save()

    dependencies = [
        ("core", "0044_alter_job_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processqgisprojectfilejob",
            old_name="feedback",
            new_name="feedback_old",
        ),
        migrations.AddField(
            model_name="job",
            name="feedback",
            field=models.JSONField(null=True),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name="exportjob",
            name="exportlog",
        ),
        migrations.RemoveField(
            model_name="processqgisprojectfilejob",
            name="feedback_old",
        ),
    ]
