# Generated by Django 3.2.8 on 2021-10-12 22:34

from django.db import migrations, models


def fill_in_datetime_fields(apps, schema_editor):
    # Old values in output field of delta table where string instead of json
    Job = apps.get_model("core", "Job")
    Job.objects.update(
        started_at=models.F("created_at"), finished_at=models.F("updated_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, editable=False),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, editable=False),
        ),
        migrations.RunPython(fill_in_datetime_fields, migrations.RunPython.noop),
    ]
