# Generated by Django 3.2.5 on 2021-07-09 23:58

from django.db import migrations
from qfieldcloud.core.utils import get_qgis_project_file


class Migration(migrations.Migration):
    def forwards_func(apps, schema_editor):
        Project = apps.get_model("core", "Project")

        for project in Project.objects.all():
            project.project_filename = get_qgis_project_file(project.id)
            project.save()

    dependencies = [
        ("core", "0045_auto_20210709_2358"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
