# Generated by Django 3.2.8 on 2021-10-20 21:35

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_auto_20211013_2304"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(
                choices_display="WITH_GMT_OFFSET", default="Europe/Zurich"
            ),
        ),
    ]
