# Generated by Django 3.2.9 on 2021-11-17 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_in_last_apply_attempt_at(apps, schema_editor):
    # Old values in output field of delta table where string instead of json
    Delta = apps.get_model("core", "Delta")
    ApplyJobDelta = apps.get_model("core", "ApplyJobDelta")

    for delta in Delta.objects.all():
        jobs_qs = ApplyJobDelta.objects.filter(delta=delta)

        if jobs_qs.count():
            job_delta = jobs_qs.latest("apply_job__started_at")
            delta.last_apply_attempt_at = job_delta.apply_job.started_at
            delta.last_apply_attempt_by = job_delta.apply_job.created_by
            delta.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_useraccount_notifs_frequency"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="last_apply_attempt_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="delta",
            name="last_apply_attempt_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(fill_in_last_apply_attempt_at, migrations.RunPython.noop),
    ]
