# Generated by Django 3.2.9 on 2021-11-25 03:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_auto_20211118_1150"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagejob",
            options={
                "verbose_name": "Job: package",
                "verbose_name_plural": "Jobs: package",
            },
        ),
        migrations.AddField(
            model_name="delta",
            name="new_geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=4, null=True, srid=0
            ),
        ),
        migrations.AddField(
            model_name="delta",
            name="old_geom",
            field=django.contrib.gis.db.models.fields.GeometryField(
                dim=4, null=True, srid=0
            ),
        ),
        migrations.AddField(
            model_name="delta",
            name="srid",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunSQL(
            """
                UPDATE core_delta
                SET
                    srid = COALESCE(NULLIF(REGEXP_REPLACE(jsonb_extract_path_text('{"localLayerCrs": ""}', 'localLayerCrs'), '\D*', '', 'g'), ''), '0')::int,
                    old_geom = ST_GeomFromText(
                        jsonb_extract_path_text(content, 'old', 'geometry')
                    ),
                    new_geom = ST_GeomFromText(
                        jsonb_extract_path_text(content, 'new', 'geometry')
                    )
            """,
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            """
                CREATE FUNCTION core_delta_geom_trigger_func()
                RETURNS trigger
                AS
                $$
                    BEGIN
                        NEW.srid := COALESCE(NULLIF(REGEXP_REPLACE(jsonb_extract_path_text(NEW.content, 'localLayerCrs'), '\D*', '', 'g'), ''), '0')::int;
                        NEW.old_geom := ST_GeomFromText( jsonb_extract_path_text(NEW.content, 'old', 'geometry') );
                        NEW.new_geom := ST_GeomFromText( jsonb_extract_path_text(NEW.content, 'new', 'geometry') );
                        RETURN NEW;
                    END;
                $$
                LANGUAGE PLPGSQL
            """,
            """
                DROP FUNCTION core_delta_geom_trigger_func();
            """,
        ),
        migrations.RunSQL(
            """
                CREATE TRIGGER core_delta_geom_update_trigger BEFORE UPDATE ON core_delta
                FOR EACH ROW
                WHEN (OLD.content IS DISTINCT FROM NEW.content)
                EXECUTE FUNCTION core_delta_geom_trigger_func()
            """,
            """
                DROP TRIGGER core_delta_geom_update_trigger ON core_delta;
            """,
        ),
        migrations.RunSQL(
            """
                CREATE TRIGGER core_delta_geom_insert_trigger BEFORE INSERT ON core_delta
                FOR EACH ROW
                EXECUTE FUNCTION core_delta_geom_trigger_func()
            """,
            """
                DROP TRIGGER core_delta_geom_insert_trigger ON core_delta
            """,
        ),
    ]
