# Generated by Django 3.2.12 on 2022-04-13 14:44

import django.core.validators
import django.db.models.deletion
import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0051_auto_20211125_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Must start with a capital letter and followed by capital letters, numbers or underscores.",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]+[A-Z0-9_]+$",
                                "Must start with a capital letter and followed by capital letters, numbers or underscores.",
                            )
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("pgservice", "pg_service"),
                            ("envvar", "Environment Variable"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secrets",
                        to="core.project",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_secrets",
                        to="core.user",
                    ),
                ),
                ("value", django_cryptography.fields.encrypt(models.TextField())),
            ],
        ),
    ]
