# Generated by Django 3.2.11 on 2022-02-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_auto_20220204_1654"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="storage_size_mb",
            field=models.FloatField(default=0),
        ),
    ]
