# Generated by Django 3.2.12 on 2022-03-09 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="last_package_job",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_job_of",
                to="core.packagejob",
            ),
        ),
    ]
