# Generated by Django 3.2.13 on 2022-05-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20220505_1948"),
    ]

    operations = [
        migrations.AddField(
            model_name="delta",
            name="jobs_to_apply",
            field=models.ManyToManyField(
                through="core.ApplyJobDelta", to="core.ApplyJob"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="last_package_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="last_job_of",
                to="core.packagejob",
            ),
        ),
    ]
