# Generated by Django 3.2.11 on 2022-02-08 20:59

import datetime

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscription", "0002_populate_plans"),
        ("core", "0054_project_last_package"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="storage_limit_mb",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="synchronizations_per_months",
        ),
        migrations.AddField(
            model_name="project",
            name="repackaging_cache_expire",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="account_type",
            new_name="plan",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="subscription.plan",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="storage_size_mb",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="projectcollaborator",
            name="collaborator",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("user_type__in", [1, 3])),
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
