# Generated by Django 3.2.11 on 2022-02-08 20:59

import datetime

import django.core.validators
import django.db.models.deletion
import qfieldcloud.subscription.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0002_populate_account_types"),
        ("core", "0055_auto_20220506_1240"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="storage_limit_mb",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="synchronizations_per_months",
        ),
        migrations.AddField(
            model_name="project",
            name="repackaging_cache_expire",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=60)
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="account_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="subscription.accounttype",
                default=qfieldcloud.subscription.models.AccountType.get_or_create_default,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="storage_size_mb",
            field=models.FloatField(default=0),
        ),
    ]
