# Generated by Django 3.2.16 on 2022-10-28 16:06

import django.db.models.deletion
import qfieldcloud.core.models
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def set_active_plan(apps, schema_editor):
    UserAccount = apps.get_model("core", "UserAccount")
    Subscription = apps.get_model("subscription", "Subscription")
    Plan = apps.get_model("subscription", "Plan")

    for account in UserAccount.objects.all():
        subscription = (
            Subscription.objects.filter(
                Q(active_until__isnull=True) | Q(active_until__gt=timezone.now())
            )
            .filter(status__startswith="active_")
            .first()
        )

        if subscription:
            plan_id = subscription.plan_id
        else:
            plan = Plan.objects.filter(
                is_default=True, user_type=account.user.type
            ).first()
            plan_id = plan.id

        account.plan_id = plan_id
        account.save(update_fields=["plan_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_auto_20220914_2049"),
        ("subscription", "0004_auto_20220923_1602"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "base_manager_name": "objects",
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelManagers(
            name="team",
            managers=[
                ("objects", qfieldcloud.core.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", qfieldcloud.core.models.UserManager()),
            ],
        ),
        # Remove UserAccount.Plan
        migrations.AlterField(
            model_name="useraccount",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="subscription.plan",
                null=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, set_active_plan),
        migrations.RemoveField(
            model_name="useraccount",
            name="plan",
        ),
        # Add is_initially_trial field to organizations
        migrations.AddField(
            model_name="organization",
            name="is_initially_trial",
            field=models.BooleanField(default=False),
        ),
    ]
