# Generated by Django 3.2.17 on 2023-02-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_auto_20221028_1806"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="storage_size_mb",
            new_name="file_storage_bytes",
        ),
        migrations.RunSQL(
            """
                UPDATE core_project
                SET
                    file_storage_bytes = file_storage_bytes * 1000 * 1000
            """,
            """
                UPDATE core_project
                SET
                    file_storage_bytes = file_storage_bytes / 1000 / 1000
            """,
        ),
        migrations.AlterField(
            model_name="project",
            name="file_storage_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
