# Generated by Django 3.2.17 on 2023-02-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0061_add_incognito_and_audit_to_collaborators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("type", 1)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_owner",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("type", 1)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_organizations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectcollaborator",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projectcollaborator",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
