# Generated by Django 3.2.17 on 2023-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0062_auto_20230216_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delta",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="delta",
            name="deltafile_id",
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name="delta",
            name="last_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("applied", "Applied"),
                    ("conflict", "Conflict"),
                    ("not_applied", "Not_applied"),
                    ("error", "Error"),
                    ("ignored", "Ignored"),
                    ("unpermitted", "Unpermitted"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="delta",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
