# Generated by Django 3.2.18 on 2023-03-28 18:17

import migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0063_auto_20230305_1551"),
    ]

    operations = [
        migrate_sql.operations.ReverseAlterSQL(
            name="core_user_email_partial_uniq",
            sql="\n            DROP INDEX IF EXISTS core_user_email_partial_uniq\n        ",
            reverse_sql="\n            CREATE UNIQUE INDEX IF NOT EXISTS core_user_email_partial_uniq ON core_user (email)\n            WHERE type = 1 AND email IS NOT NULL AND email != ''\n        ",
        ),
        migrate_sql.operations.AlterSQL(
            name="core_user_email_partial_uniq",
            sql="\n            CREATE UNIQUE INDEX IF NOT EXISTS core_user_email_partial_uniq ON core_user (UPPER(email))\n            WHERE type = 1 AND email IS NOT NULL AND email != ''\n        ",
            reverse_sql="\n            DROP INDEX IF EXISTS core_user_email_partial_uniq\n        ",
        ),
    ]
