# Generated by Django 3.2.18 on 2023-04-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20230328_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='container_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='static_status',
            field=models.CharField(choices=[('ok', 'Ok'), ('busy', 'Busy'), ('failed', 'Failed'), ('deleted', 'Deleted')], default='ok', max_length=32),
        ),
    ]
