# Generated by Django 3.2.18 on 2023-04-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0064_auto_20230328_2017"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("started", "Started"),
                    ("finished", "Finished"),
                    ("stopped", "Stopped"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
