# Generated by Django 3.2.18 on 2023-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0066_delta_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="docker_finished_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="docker_started_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
