# Generated by Django 3.2.18 on 2023-05-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0067_auto_20230515_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="container_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
