# Generated by Django 3.2.18 on 2023-06-16 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0068_job_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="storage_keep_versions",
            field=models.PositiveIntegerField(
                verbose_name="File versions to keep",
                help_text=(
                    "Use this value to limit the maximum number of file versions. If empty, your current plan's default will be used. Available to Premium users only."
                ),
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                null=True,
                blank=True,
            ),
        )
    ]
