# Generated by Django 3.2.18 on 2023-06-16 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_job_container_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_premium",
            field=models.BooleanField(
                default=False, help_text="Whether the project's owner is a premium user"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="storage_keep_versions",
            field=models.PositiveIntegerField(
                default=3,
                help_text="If enabled, QFieldCloud will use this value to limit the maximum number of versions per file in the current project with this value. If the value is larger than the maximum number of versions per file your current plan entitles you to, the current plan's value will be used instead (by default 3 for non-paying customers; 10 for paying customers)",
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
