# Generated by Django 3.2.18 on 2023-07-17 20:44

import migrate_sql.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_auto_20230717_2243"),
    ]

    operations = [
        migrate_sql.operations.CreateSQL(
            name="core_delta_geom_insert_trigger",
            sql="\n            CREATE TRIGGER core_delta_geom_insert_trigger BEFORE INSERT ON core_delta\n            FOR EACH ROW\n            EXECUTE FUNCTION core_delta_geom_trigger_func()\n        ",
            reverse_sql="\n            DROP TRIGGER IF EXISTS core_delta_geom_insert_trigger ON core_delta\n        ",
        ),
    ]
