# Generated by Django 3.2.18 on 2023-07-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0071_auto_20230717_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="remaining_trial_organizations",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Remaining trial organizations the user can create.",
            ),
        ),
    ]
