# Generated by Django 3.2.23 on 2024-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0072_person_remaining_trial_organizations"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="packaging_offliner",
            field=models.CharField(
                choices=[
                    ("qgiscore", "QGIS Core Offline Editing"),
                    ("pythonmini", "Optimized Offliner"),
                ],
                default="pythonmini",
                help_text=(
                    'The packaging offliner is used withing jobs to convert QGIS projects into QField projects. The new "Optimized Offliner" should be selected over the legacy "QGIS Core Offline Editing" for new projects.'
                ),
                max_length=100,
                verbose_name="Packaging Offliner",
            ),
        ),
    ]
