# Generated by Django 3.2.25 on 2024-09-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="packaging_offliner",
            field=models.CharField(
                choices=[
                    ("qgiscore", "QGIS Core Offline Editing (deprecated)"),
                    ("pythonmini", "Optimized Packager"),
                ],
                default="pythonmini",
                help_text='The Packaging Offliner packages data for offline use with QField. The new "Optimized Packager" should be preferred over the deprecated "QGIS Core Offline Editing" for new projects.',
                max_length=100,
                verbose_name="Packaging Offliner",
            ),
        ),
    ]
