# Generated by Django 4.2.16 on 2024-11-24 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0078_alter_project_packaging_offliner"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organization_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="organizationmember",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_organization_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
