# Generated by Django 4.2.17 on 2025-01-23 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0079_organizationmember_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="project_filename",
            new_name="the_qgis_file_name",
        ),
    ]
