# Generated by Django 3.2.25 on 2024-06-18 01:02

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import qfieldcloud.core.models
import qfieldcloud.core.validators
from qfieldcloud.core.fields import QfcImageField


def get_file_storage_name():
    return settings.LEGACY_STORAGE_NAME or "default"


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0080_rename_project_filename_project_the_qgis_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_locked",
            field=models.BooleanField(
                default=False,
                help_text="If set to true, the project is temporarily locked. Locking is internal QFieldCloud mechanism related to file storage migration or other file operations.",
                verbose_name="Is locked",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="file_storage",
            field=models.CharField(
                editable=False,
                help_text="Which file storage provider should be used for the storing the project related files.",
                max_length=100,
                validators=[qfieldcloud.core.validators.file_storage_name_validator],
                verbose_name="File storage",
                default=get_file_storage_name,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="file_storage",
            field=models.CharField(
                editable=False,
                help_text="Which file storage provider should be used for the storing the project related files.",
                max_length=100,
                validators=[qfieldcloud.core.validators.file_storage_name_validator],
                verbose_name="File storage",
                default=qfieldcloud.core.models.get_project_file_storage_default,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="file_storage_migrated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="File Storage Migrated At",
            ),
        ),
        migrations.RenameField(
            model_name="project",
            old_name="thumbnail_uri",
            new_name="legacy_thumbnail_uri",
        ),
        migrations.AlterField(
            model_name="project",
            name="legacy_thumbnail_uri",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Legacy Thumbnail Picture URI"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=qfieldcloud.core.fields.DynamicStorageFileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=qfieldcloud.core.models.get_project_thumbnail_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg")
                    )
                ],
                verbose_name="Thumbnail Picture",
            ),
        ),
        migrations.RenameField(
            model_name="useraccount",
            old_name="avatar_uri",
            new_name="legacy_avatar_uri",
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="legacy_avatar_uri",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Legacy Profile Picture URI"
            ),
        ),
        migrations.AddField(
            model_name="useraccount",
            name="avatar",
            field=QfcImageField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=qfieldcloud.core.models.get_user_account_avatar_upload_to,
                verbose_name="Avatar Picture",
            ),
        ),
    ]
