# Generated by Django 4.2.19 on 2025-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0082_project_attachments_file_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="If set to true, the project will always appear on top of the project list, no matter the sorting. If multiple projects are featured, they will be sorted by the user defined sorting.",
                verbose_name="Is sticky",
            ),
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-is_featured", "owner__username", "name"]},
        ),
    ]
