# Generated by Django 4.2.19 on 2025-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_project_is_sticky"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_attachment_download_on_demand",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, it indicates to the client (e.g. QField) that the attachments may be downloaded on demand.",
            ),
        ),
    ]
