# Generated by Django 4.2.19 on 2025-05-01 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_assigned_secrets(apps, schema_editor):
    Secret = apps.get_model("core", "Secret")

    Secret.objects.filter(
        assigned_to__isnull=False,
    ).delete()


def set_job_triggered_by(apps, schema_editor):
    Job = apps.get_model("core", "Job")

    Job.objects.update(
        triggered_by=models.F("created_by"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0084_project_is_attachment_download_on_demand"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="secret",
            options={"ordering": ["project", "assigned_to", "organization"]},
        ),
        migrations.RemoveConstraint(
            model_name="secret",
            name="secret_project_name_uniq",
        ),
        migrations.AddField(
            model_name="secret",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="secret",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 2)),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="core.organization",
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=models.Q(("type", 1)),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_secrets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "assigned_to", "organization"),
                name="secret_project_name_assigned_to_organization_uniq",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, delete_assigned_secrets),
        migrations.RemoveConstraint(
            model_name="secret",
            name="secret_project_name_assigned_to_organization_uniq",
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("project", "type", "name", "assigned_to"),
                name="secret_project_type_name_assigned_to_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("organization", "type", "name", "assigned_to"),
                name="secret_organization_type_name_assigned_to_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("project__isnull", True),
                    ("organization__isnull", True),
                    _connector="XOR",
                ),
                name="secret_assigned_to_organization_or_user",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="triggered_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("type", 1)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_jobs",
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
        ),
        migrations.RunPython(
            set_job_triggered_by,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="job",
            name="triggered_by",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("type", 1)),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="triggered_jobs",
                to=settings.AUTH_USER_MODEL,
                null=False,
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="project",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="core.project",
            ),
        ),
    ]
