# Generated by Django 4.2.19 on 2025-05-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_alter_secret_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secret",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="core.project",
            ),
        ),
        migrations.RemoveField(
            model_name="project",
            name="last_package_job",
        ),
    ]
