# Generated by Django 4.2.19 on 2025-06-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_alter_secret_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_attachment_download_on_demand',
            field=models.BooleanField(default=False, help_text='If enabled, it indicates that attachments should be downloaded on demand.'),
        ),
    ]
