# Generated by Django 4.2.19 on 2025-07-14 09:01

import django_cryptography.fields
from django.db import migrations, models
from encrypted_fields.fields import EncryptedTextField


def copy_secret_value(apps, schema_editor):
    Secret = apps.get_model("core", "Secret")

    # Warning: this operation might be slow if there are many secrets in the database.
    for secret in Secret.objects.all():
        secret.value = secret.old_value
        secret.save(update_fields=["value"])


def revert_secret_value(apps, schema_editor):
    Secret = apps.get_model("core", "Secret")

    # Warning: this operation might be slow if there are many secrets in the database.
    for secret in Secret.objects.all():
        secret.old_value = secret.value
        secret.save(update_fields=["old_value"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_alter_secret_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secret",
            old_name="value",
            new_name="old_value",
        ),
        migrations.AddField(
            model_name="secret",
            name="value",
            field=EncryptedTextField(default="", blank=True, null=True),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_secret_value,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="secret",
            name="old_value",
            field=django_cryptography.fields.encrypt(
                models.TextField(blank=True, null=True)
            ),
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=revert_secret_value,
        ),
        migrations.AlterField(
            model_name="secret",
            name="value",
            field=EncryptedTextField(blank=False, null=False),
        ),
    ]
