# Generated by Django 4.2.19 on 2025-07-14 09:01

from django.db import migrations, models
from encrypted_fields.fields import EncryptedTextField


def copy_secret_value(apps, schema_editor):
    Secret = apps.get_model("core", "Secret")
    # is this going to decrypt the value as we want ?
    Secret.objects.update(
        value=models.F("old_value"),
    )

    # if above doesn't decrypt the value -> slower solution
    # for secret in Secret.objects.all():
    #     secret.value = secret.old_value
    #     secret.save(update_fields=["value"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0085_alter_secret_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="secret",
            old_name="value",
            new_name="old_value",
        ),
        migrations.AddField(
            model_name="secret",
            name="value",
            field=EncryptedTextField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_secret_value,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
