# Generated by Django 4.2.23 on 2025-09-09 19:03

import django.db.models.deletion
from django.db import migrations, models

import qfieldcloud.core.fields
import qfieldcloud.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0086_secret_new_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaultyDeltaFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deltafile_id",
                    models.UUIDField(
                        editable=False, null=True, verbose_name="Deltafile ID"
                    ),
                ),
                (
                    "deltafile",
                    qfieldcloud.core.fields.DynamicStorageFileField(
                        max_length=1024,
                        upload_to=qfieldcloud.core.models.get_faulty_deltafile_upload_to,
                        verbose_name="Deltafile",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faulty_deltafiles",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faulty deltafile",
            },
        ),
    ]
