# Generated by Django 4.2.24 on 2025-09-17 07:20

from django.db import migrations, models

import qfieldcloud.core.models
import qfieldcloud.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0087_faultydeltafile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file_storage",
            field=models.CharField(
                default=qfieldcloud.core.models.get_project_file_storage_default,
                help_text="Which file storage provider should be used for the storing the project related files.",
                max_length=100,
                validators=[qfieldcloud.core.validators.file_storage_name_validator],
                verbose_name="File storage",
            ),
        ),
    ]
