# Generated by Django 4.2.24 on 2025-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0088_alter_project_file_storage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="is_locked",
        ),
        migrations.AddField(
            model_name="project",
            name="locked_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="If not null, it means that the project is being migrated, and the datetime represents when the project was temporarily locked. Locking is internal QFieldCloud mechanism related to file storage migration or other file operations.",
                null=True,
                verbose_name="Locked at",
            ),
        ),
    ]
