# Generated by Django 4.2.25 on 2025-10-09 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0089_remove_project_is_locked_project_locked_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="is_geodb_enabled",
        ),
        migrations.DeleteModel(
            name="Geodb",
        ),
    ]
