# Generated by Django 4.2.25 on 2025-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0091_remove_geodb"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="restricted_data_last_updated_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Restricted data last updated at",
            ),
        ),
    ]
