# Generated by Django 4.2.25 on 2025-11-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0092_project_restricted_data_last_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="are_attachments_versioned",
            field=models.BooleanField(
                default=True,
                help_text="If enabled, attachment files will make use of the file versioning system. If disabled, only the latest version of each attachment file will be kept, and stored with the extension in the filename.",
                verbose_name="Versioned attachment files",
            ),
        ),
    ]
