# Generated by Django 4.2.26 on 2025-12-03 12:54

from django.db import migrations, models

import qfieldcloud.core.models
import qfieldcloud.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0093_project_are_attachments_versioned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="are_attachments_versioned",
            field=models.BooleanField(
                default=qfieldcloud.core.models.get_project_are_attachments_versioned_default,
                help_text="If enabled, attachment files will make use of the file versioning system. If disabled, only the latest version of each attachment file will be kept, and stored with the extension in the filename.",
                verbose_name="Versioned attachment files",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="attachments_file_storage",
            field=models.CharField(
                default=qfieldcloud.core.models.get_project_attachments_file_storage_default,
                help_text="Which file storage provider should be used for storing the project attachments files.",
                max_length=100,
                validators=[qfieldcloud.core.validators.file_storage_name_validator],
                verbose_name="Attachments file storage",
            ),
        ),
    ]
