# Generated by Django 4.2.26 on 2025-11-18 12:10

import django.db.models.deletion
from django.contrib.gis.db import models as gis_models
from django.db import migrations, models

import qfieldcloud.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_project_are_attachments_versioned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="type",
            field=models.CharField(
                choices=[
                    ("package", "Package"),
                    ("delta_apply", "Delta Apply"),
                    ("process_projectfile", "Process QGIS Project File"),
                    ("create_project", "Create Project"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ProjectSeed",
            fields=[
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="core.project",
                    ),
                ),
                (
                    "xlsform_file",
                    models.FileField(
                        max_length=1024,
                        upload_to=qfieldcloud.core.models.get_seed_xlsform_upload_to,
                    ),
                ),
                ("settings", models.JSONField()),
                (
                    "extent",
                    gis_models.PolygonField(
                        null=False,
                        blank=False,
                        srid=3857,
                    ),
                ),
                (
                    "copy_from_project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="derived_seeds",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
