# Generated by Django 4.2.28 on 2026-02-17 17:22

import django.core.validators
from django.db import migrations

import qfieldcloud.core.fields
import qfieldcloud.core.models
import qfieldcloud.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_alter_project_are_attachments_versioned_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=qfieldcloud.core.fields.DynamicStorageFileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=qfieldcloud.core.models.get_project_thumbnail_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg")
                    ),
                    qfieldcloud.core.validators.MaxImageDimensionValidator(10000),
                    qfieldcloud.core.validators.MaxFileSizeValidator(5242880),
                ],
                verbose_name="Thumbnail Picture",
            ),
        ),
    ]
