# Generated by Django 5.2.11 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_alter_project_thumbnail"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="secret",
            name="secret_project_type_name_assigned_to_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="secret",
            name="secret_organization_type_name_assigned_to_uniq",
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("project", "type", "name", "assigned_to"),
                name="secret_project_type_name_assigned_to_uniq",
                nulls_distinct=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="secret",
            constraint=models.UniqueConstraint(
                fields=("organization", "type", "name", "assigned_to"),
                name="secret_organization_type_name_assigned_to_uniq",
                nulls_distinct=True,
            ),
        ),
    ]
