# Generated by Django 4.2.28 on 2026-02-11 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0096_remove_secret_secret_project_type_name_assigned_to_uniq_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="legacy_thumbnail_uri",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="legacy_avatar_uri",
        ),
    ]
