# Generated by Django 5.2.12 on 2026-04-01 13:23

import django.db.models.deletion
from django.db import migrations, models

import qfieldcloud.core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_alter_job_type_projectseed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectseed",
            name="copy_from_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_seeds",
                to="core.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectseed",
            name="xlsform_file",
            field=models.FileField(
                blank=True,
                max_length=1024,
                null=True,
                upload_to=qfieldcloud.core.models.get_seed_xlsform_upload_to,
            ),
        ),
    ]
