# Generated by Django 5.2.13 on 2026-04-16 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_alter_projectseed_copy_from_project_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectseed",
            old_name="copy_from_project",
            new_name="clone_from_project",
        ),
    ]
