# Generated by Django 5.2.13 on 2026-04-22 09:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0098_alter_projectseed_copy_from_project_and_more"),
    ]

    operations = [
        # Unfortunately there is no easy way to alter the SRID of a geometry field in Django,
        # so we need to use raw SQL to perform the transformation.
        migrations.RunSQL(
            sql="""
                ALTER TABLE core_projectseed
                ALTER COLUMN extent
                TYPE geometry(POLYGON, 4326)
                USING ST_Transform(extent, 4326);
            """,
            reverse_sql="""
                ALTER TABLE core_projectseed
                ALTER COLUMN extent
                TYPE geometry(POLYGON, 3857)
                USING ST_Transform(extent, 3857);
            """,
        ),
        migrations.AlterField(
            model_name="projectseed",
            name="extent",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
