# Generated by Django 5.2.13 on 2026-04-17 11:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_rename_copy_from_project_projectseed_clone_from_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectseed",
            name="extent",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=3857
            ),
        ),
    ]
