# Generated by Django 5.2.13 on 2026-04-22 13:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_alter_projectseed_extent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectseed',
            old_name='copy_from_project',
            new_name='clone_from_project',
        ),
        migrations.AlterField(
            model_name='projectseed',
            name='extent',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
