# Generated by Django 5.2.13 on 2026-05-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0101_rename_copy_from_project_projectseed_clone_from_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="qgis_version",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The QGIS project version as detected from the uploaded project file.",
                max_length=100,
                null=True,
                verbose_name="QGIS project version",
            ),
        ),
    ]
