# Generated by Django 5.2.14 on 2026-07-06 07:52

# This migration only removes the fields from the `core` app's Django state,
# it does not run ALTER TABLE DROP COLUMN on the database.
#
# The columns are FKs still used elsewhere, so they must stay in the DB. They
# are re-added to the Django state by the `project` app's initial migration.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0102_project_qgis_version"),
    ]

    state_operations = [
        migrations.RemoveField(
            model_name="project",
            name="last_package_job",
        ),
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
