# Generated by Django 5.2.14 on 2026-07-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0103_detach_project_fks_from_state"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="Project",
            table="project_project",
        ),
        migrations.AlterField(
            model_name="projectcollaborator",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="secret",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="secrets",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectseed",
            name="clone_from_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="derived_seeds",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="faultydeltafile",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faulty_deltafiles",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="projectseed",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="seed",
                serialize=False,
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="delta",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deltas",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="project.project",
            ),
        ),
    ]
