# Generated by Django 5.2.14 on 2026-07-06 09:01

# This migration only removes the `Project` model from the `core` app's Django
# state, it does not run DROP TABLE on the database.
#
# The table stays in the DB and is re-added to the Django state by
# `project/migrations/0001_initial.py`.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0104_alter_projectcollaborator_project_and_more"),
        ("filestorage", "0009_alter_file_project"),
    ]

    state_operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
