# Generated by Django 5.2.14 on 2026-07-06 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0105_detach_project_from_db_state"),
        ("project", "0002_projectseed"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ProjectSeed",
            table="project_projectseed",
        ),
    ]
