# Generated by Django 5.2.14 on 2026-07-06 12:17

# This migration only removes the `ProjectSeed` model from the `core` app's
# Django state, it does not run DROP TABLE on the database.
#
# The table stays in the DB and is re-added to the Django state by
# `project/migrations/0002_projectseed.py`.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0106_alter_projectseed_table"),
    ]

    state_operations = [
        migrations.DeleteModel(
            name="ProjectSeed",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
