# Generated by Django 5.2.16 on 2026-07-20 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0107_detach_project_seed_from_db_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="twitter",
        ),
    ]
