# Generated by Django 5.2.16 on 2026-08-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0108_remove_useraccount_twitter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("creator", "Creator"),
                    ("member", "Member"),
                ],
                default="member",
                max_length=10,
            ),
        ),
    ]
