# Generated by Django 2.2.6 on 2020-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200212_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='absolute_path',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
