# Generated by Django 2.2.6 on 2020-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_auto_20200309_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='absolute_path',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
