# Generated by Django 2.2.6 on 2020-03-12 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200312_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileversion',
            old_name='stored_path',
            new_name='original_path',
        ),
    ]
