# Generated by Django 2.2.6 on 2020-03-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_fileversion_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(limit_choices_to=models.Q(user_type=2), on_delete=django.db.models.deletion.CASCADE, related_name='members', to='model.Organization'),
        ),
    ]
