# Generated by Django 2.2.6 on 2020-04-27 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_auto_20200327_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeltaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.SmallIntegerField()),
                ('layer_id', models.TextField()),
                ('feature_id', models.UUIDField()),
                ('old_geometry', models.TextField(blank=True)),
                ('new_geometry', models.TextField(blank=True, null=True)),
                ('old_attributes', models.TextField(blank=True)),
                ('new_attributes', models.TextField(blank=True)),
                ('delta_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.DeltaFile')),
            ],
        ),
    ]
