# Generated by Django 2.2.6 on 2020-06-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_auto_20200608_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delta',
        ),
    ]
