# Generated by Django 3.2.12 on 2022-03-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authtoken",
            name="client_type",
            field=models.CharField(
                choices=[
                    ("browser", "Browser"),
                    ("cli", "Command line interface"),
                    ("sdk", "SDK"),
                    ("qfield", "QField"),
                    ("qfieldsync", "QFieldSync"),
                    ("worker", "Worker"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
    ]
