# Generated by Django 4.2.16 on 2024-12-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_authtoken_client_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="authtoken",
            index=models.Index(
                fields=["created_at"], name="authenticat_created_ee68f9_idx"
            ),
        ),
    ]
