# Generated by Django 4.2.16 on 2024-09-23 20:56

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

import qfieldcloud.core.fields
import qfieldcloud.core.validators
import qfieldcloud.filestorage.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0081_file_storage_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(255),
                            qfieldcloud.core.validators.MaxBytesLengthValidator(1024),
                            django.core.validators.ProhibitNullCharactersValidator(),
                            django.core.validators.RegexValidator(
                                '^(?!.*[<>:"/\\\\|?*])(?!(?:COM[0-9]|CON|LPT[0-9]|NUL|PRN|AUX|com[0-9]|con|lpt[0-9]|nul|prn|aux)$)[^\\\\\\/:*"?<>|]{1,255}(?<![\\s\\.])$',
                                'The filename must not contain forbidden characters (<>:"/\\|?*) or Windows reserved words (CON, LPT[0-9], NUL, PRN, AUX).',
                            ),
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Project File"),
                            (2, "Package File"),
                        ],
                        editable=False,
                    ),
                ),
                (
                    "package_job",
                    models.ForeignKey(
                        on_delete=models.DO_NOTHING,
                        editable=False,
                        limit_choices_to=models.Q(type="package"),
                        null=True,
                        to="core.Job",
                    ),
                ),
                ("latest_version_count", models.PositiveIntegerField(default=0)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    qfieldcloud.core.fields.DynamicStorageFileField(
                        max_length=1024,
                        upload_to=qfieldcloud.filestorage.models.get_file_version_upload_to,
                        null=False,
                        blank=False,
                        editable=False,
                    ),
                ),
                ("etag", models.TextField(max_length=255, editable=False)),
                ("md5sum", models.BinaryField(max_length=16, editable=False)),
                ("sha256sum", models.BinaryField(max_length=32, editable=False)),
                ("size", models.PositiveIntegerField(editable=False)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        editable=False,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=timezone.now, editable=False),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="filestorage.file",
                        editable=False,
                    ),
                ),
                (
                    "legacy_id",
                    models.TextField(max_length=255, editable=False, null=True),
                ),
            ],
            options={"ordering": ("file", "-uploaded_at")},
        ),
        migrations.AddField(
            model_name="file",
            name="latest_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="filestorage.fileversion",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="project",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
                related_name="all_files",
            ),
        ),
    ]
