# Generated by Django 4.2.19 on 2025-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0003_alter_file_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="size",
            field=models.PositiveBigIntegerField(editable=False),
        ),
    ]
