# Generated by Django 5.2.11 on 2026-03-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0096_remove_secret_secret_project_type_name_assigned_to_uniq_and_more",
        ),
        ("filestorage", "0005_fileversion_file_storage"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="file",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                fields=("project", "name", "file_type", "package_job"),
                name="unique_file_per_project_name_type_packagejob",
                nulls_distinct=False,
            ),
        ),
    ]
