# Generated by Django 5.2.13 on 2026-05-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0006_alter_file_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fileversion",
            name="legacy_id",
        ),
        migrations.AlterField(
            model_name="file",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="fileversion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
