# Generated by Django 5.2.13 on 2026-05-17 08:10

import django.core.validators
from django.db import migrations, models

import qfieldcloud.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0007_alter_file_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.MaxLengthValidator(255),
                    qfieldcloud.core.validators.MaxBytesLengthValidator(1024),
                    django.core.validators.ProhibitNullCharactersValidator(),
                    django.core.validators.RegexValidator(
                        '^(?!.*[<>:"/\\\\|?*\\x00-\\x1f\\x7f])(?!(?:COM[0-9]|CON|LPT[0-9]|NUL|PRN|AUX|com[0-9]|con|lpt[0-9]|nul|prn|aux)$)[^\\\\\\/:*"?<>|\\x00-\\x1f\\x7f]{1,255}(?<![\\s\\.])$',
                        'The filename must not contain forbidden characters (<>:"/\\|?*) or Windows reserved words (CON, LPT[0-9], NUL, PRN, AUX).',
                    ),
                ],
            ),
        ),
    ]
