# Generated by Django 5.2.14 on 2026-07-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filestorage", "0008_alter_file_name"),
        ("project", "0001_initial"),
        ("core", "0104_alter_projectcollaborator_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="project",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_files",
                to="project.project",
            ),
        ),
    ]
